### ISSUE TITLE
Cascade Layers support

### ISSUE THREAD

**Issue by tim-richter** [ant-design/ant-design-icons#644]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Since antd introduced a way to apply cascade layers to their styles (https://ant.design/docs/react/compatible-style#layer-downgrade), I was wondering, if we could support this for the icons as well.

Currently all of the injected styles from this library would have a higher specificity, then antd styles, if used together with `layer`. This could cause specificity issues in the long run.
It would also make it easier for antd users, to use icons in their projects, if those would automatically get the same specificity layer as antd styles.
 
I could see two possible solutions to this:
- Letting the `IconContext` set this for all icons and then using the context to conditionally wrap the iconStyles with the `antd` layer (probably easiest to do)
- Applying the styles from this repo via `@ant-design/css-in-js`. Since we have to set `layer` already on the `@ant-design/css-in-js`, this should make sure the layer is also applied to the icons as well.

Let me know which solutions would work best and if I can help with any of those.

**Comment by skycrazyk** [comment]
There is already problem with icons when using `@layer`. `@ant-design/icons` has more specific styles and overrides `antd` styles.

I reproduced the problem on stackblitz https://stackblitz.com/edit/vitejs-vite-cdw4gw?file=src%2FApp.tsx

![image](https://github.com/ant-design/ant-design-icons/assets/7424691/450366fc-3825-435f-b860-f2d7fc7bee99)

![image](https://github.com/ant-design/ant-design-icons/assets/7424691/d046c9d4-5a9a-4212-888a-463e4cf8c98a)

**Comment by tim-richter** [comment]
@vagusX @MadCcc @afc163 Sorry for tagging here, but thanks to the reproduction from @skycrazyk, I guess there are already specificity problems with the icons library, and I think this should be fixed rather sooner than later.

**Comment by Hourglasser23** [comment]
This is still problem with in 5.3.7 [@ant-design/icons](https://github.com/ant-design/ant-design-icons/blob/master/packages/icons-react). Icons are black even though they should by colored by css-in-js provided @layer solution.

Tried patching the package and remove var iconStyles in utils.js, but it has not desired side effects (as loader icon not loading,...) https://github.com/ant-design/ant-design-icons/blob/master/packages/icons-react/src/utils.ts (LN100). 
Better solution was to add `@layer antd` before all classes but these styles (without my patch) got injected from different part of code or by styling provider.  

Any update on proper fix on package level? Thanks so much

**Comment by chqcose** [comment]
same problem

**Comment by natunodesign** [comment]
Same problem here, any updates?

**Comment by tim-richter** [comment]
Has been fixed in 5.6.0: https://github.com/ant-design/ant-design-icons/pull/681

**Comment by luc-marongiu** [comment]
I don't think it's fixed.

Even using
```js
<StyleProvider layer>
    <App />
</StyleProvider>
```

and in tailwind.css with tailwind v4 : 
```css
@layer reset, theme, base, antd, components, utilities;
@import url(antd/dist/reset.css) layer(reset);
@import 'tailwindcss';
```

Ant Design icons are still black because some styles still do not seem to be inside a layer which causes them to override Ant Design's colors :
![Image](https://github.com/user-attachments/assets/65741a15-e48a-4925-8782-94b7a3c479af)

**Comment by tim-richter** [comment]
For us it works. Since icons are a dependency of antd, you have to update it to latest for it to work globally.

Otherwise please open a new issue with a reproduction.

**Comment by killthecreator** [comment]
Hello there, can confirm, that updating `antd` fixed the issue for me ( from `5.23.2` to  `5.24.4`)

**Comment by epavanello** [comment]
the error remains for me with the following latest verisons:
  '@ant-design/cssinjs': 1.23.0
  '@ant-design/icons': 5.6.1
  antd: 5.24.6

I still have unlayered .anticon class, that override the layered one

![Image](https://github.com/user-attachments/assets/16db321c-8204-4ade-9b8d-fa6b4aff7b2a)

Actually I bypassed the issue with this css hack

`
.anticon {
  /* Css hack, restore layer priority */
  color: revert-layer;
}
`

**Comment by skycrazyk** [comment]
@luc-marongiu, deleting `yarn.lock` and `node_modules` has resolved the [same problem](https://github.com/ant-design/ant-design-icons/issues/644#issuecomment-2627575955) for me. However, I still have another issue: incorrect priority level, even when I manually declare it in my global.css file.

<img width="400" height="465" alt="Image" src="https://github.com/user-attachments/assets/7133aeb3-31c5-4bd5-a33a-1b3a24763aae" />

<img width="400" height="236" alt="Image" src="https://github.com/user-attachments/assets/f8a99e75-4092-4d28-9289-9f7654e0cd46" />

I think this happens because `@ant-design/icons` prepends their styles in the `head` tag and I am unable to change this behavior.

<img width="400" height="776" alt="Image" src="https://github.com/user-attachments/assets/a93b1313-fc97-471a-b9d7-fcf4f32ab9f7" />
