### ISSUE TITLE
Unexpected warning

### ISSUE THREAD

**Issue by orzyyyy** [ant-design/ant-design-icons#99]
https://codesandbox.io/s/antd-reproduction-template-sn4qw

`Warning: [@ant-design/icons] icon should be icon definiton, but got [object Object]`

**Comment by vagusX** [comment]
resolved in https://github.com/ant-design/ant-design-icons/pull/102
demo: https://codesandbox.io/embed/antd-reproduction-template-f4exh

**Comment by songjinzhou** [comment]
How did it work out?

**Comment by darcydev** [comment]
Note that this is not fixed - am getting same error. 

Also it appears to be more than just an unexpected warning - is causes the `allowClear` on the `Select` component to not show the delete icon to remove the tag

![image](https://user-images.githubusercontent.com/38367944/149061238-fc57fc29-17e6-46c2-b141-70ae844d9fd1.png)

**Comment by migokcek** [comment]
I have the same issue and making @ant-design/icons-svg as a dependencies is not working. I believe webpack causes this issue but couldn't figure it out. is anyone solve this?
